### ISSUE TITLE
Error while cleaning up and build fails

### ISSUE THREAD

**Issue by gnosthi** [dyindude/gentoo-packer#17]
Build fails at end with error:

   virtualbox-iso:
==> virtualbox-iso: Executing local command: rm -rfy packages/*
    virtualbox-iso: rm: illegal option -- y
    virtualbox-iso: usage: rm [-f | -i] [-dPRrvW] file ...
    virtualbox-iso:        unlink file
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Erroneous exit code 64 while executing command: rm -rfy packages/*

Please see output above for more information.

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Erroneous exit code 64 while executing command: rm -rfy packages/*

Please see output above for more information.

==> Builds finished but no artifacts were created.

**Comment by dyindude** [comment]
I'm working through converting this to use a tarball instead of a directory, because the download file provisioner for packer is giving me inconsistent results (even though I'm using the same paths for the upload..)

This should resolve the issue once implemented

**Comment by dyindude** [comment]
Current master branch fixes this issue, feel free to test. I'll close this issue in a few days if I don't get feedback
